"""AETHER feasibility synthesis scorecard.

This file documents the synthesis layer generated by the PowerShell sync
script. The scorecard is a reader-facing aggregation over existing model
outputs; it is not a replacement for the underlying physical, cost, energy,
carbon-cycle, storage, robotics, and uncertainty models.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FeasibilityGate:
    gate: str
    status: str
    quantitative_anchor: str
    current_read: str
    main_failure_mode: str
    required_next_proof: str


VALID_STATUSES = {
    "conditional_pass",
    "upper_tail_dependency",
    "major_bottleneck",
    "research_gap",
    "governance_constraint",
}


def validate_gate(gate: FeasibilityGate) -> None:
    if gate.status not in VALID_STATUSES:
        raise ValueError(f"Unknown status: {gate.status}")
    if not gate.quantitative_anchor:
        raise ValueError(f"Missing quantitative anchor for {gate.gate}")
