"""AETHER conversion and storage-state ledger.

This script reproduces the CSV outputs generated by the PowerShell sync layer.
It intentionally keeps the arithmetic simple and auditable: mass fractions,
density-based volumes, and thermodynamic energy floors. It does not model
compression work, transport, real electrochemical overpotentials, lifecycle
emissions, or site-specific mineralization kinetics.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TABLE_DIR = ROOT / "analysis" / "tables"
DATA_DIR = ROOT / "data" / "parameters"

TARGET_GTCO2_Y = 100.0
CO2_MOLAR_MASS = 44.0095
CARBON_MOLAR_MASS = 12.011
O2_MOLAR_MASS = 31.998
MAGNESITE_MOLAR_MASS = 84.313
CO2_GAS_DENSITY_STP = 1.98
SUPERCRITICAL_CO2_DENSITY = 600.0
GRAPHITE_DENSITY = 2200.0
LIQUID_O2_DENSITY = 1141.0
MAGNESITE_DENSITY = 3000.0
CAPTURE_ENERGY_GJ_T = 3.0
SPLITTING_ENERGY_GJ_T = 8.94
WORLD_GRAPHITE_PRODUCTION_T_Y = 1_800_000.0
WORLD_GRAPHITE_RESOURCES_T = 800_000_000.0


def energy_twh(gj_per_t: float) -> float:
    return gj_per_t * TARGET_GTCO2_Y * 277.77777777777777


def volume_km3(gt: float, density_kg_m3: float) -> float:
    return gt * 1e12 / density_kg_m3 / 1e9


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    carbon_fraction = CARBON_MOLAR_MASS / CO2_MOLAR_MASS
    o2_fraction = O2_MOLAR_MASS / CO2_MOLAR_MASS
    magnesite_ratio = MAGNESITE_MOLAR_MASS / CO2_MOLAR_MASS

    carbon_gt = TARGET_GTCO2_Y * carbon_fraction
    o2_gt = TARGET_GTCO2_Y * o2_fraction
    magnesite_gt = TARGET_GTCO2_Y * magnesite_ratio

    state_rows = [
        {
            "storage_state": "CO2 gas at STP",
            "mass_or_product_gt_y": round(TARGET_GTCO2_Y, 3),
            "density_kg_m3": CO2_GAS_DENSITY_STP,
            "volume_km3_y": round(volume_km3(TARGET_GTCO2_Y, CO2_GAS_DENSITY_STP), 1),
            "additional_conversion_energy_gj_tco2": 0.0,
            "additional_conversion_energy_twh_y": 0.0,
            "average_power_tw": 0.0,
            "interpretation": "Too bulky for serious planetary storage.",
        },
        {
            "storage_state": "Supercritical CO2",
            "mass_or_product_gt_y": round(TARGET_GTCO2_Y, 3),
            "density_kg_m3": SUPERCRITICAL_CO2_DENSITY,
            "volume_km3_y": round(volume_km3(TARGET_GTCO2_Y, SUPERCRITICAL_CO2_DENSITY), 1),
            "additional_conversion_energy_gj_tco2": 0.0,
            "additional_conversion_energy_twh_y": 0.0,
            "average_power_tw": 0.0,
            "interpretation": "Dense default CO2 storage state, subject to storage constraints.",
        },
        {
            "storage_state": "Solid carbon from full splitting",
            "mass_or_product_gt_y": round(carbon_gt, 3),
            "density_kg_m3": GRAPHITE_DENSITY,
            "volume_km3_y": round(volume_km3(carbon_gt, GRAPHITE_DENSITY), 2),
            "additional_conversion_energy_gj_tco2": SPLITTING_ENERGY_GJ_T,
            "additional_conversion_energy_twh_y": round(energy_twh(SPLITTING_ENERGY_GJ_T), 0),
            "average_power_tw": round(energy_twh(SPLITTING_ENERGY_GJ_T) / 8760.0, 2),
            "interpretation": "Compact but energy-expensive special case.",
        },
        {
            "storage_state": "Liquid O2 coproduct from full splitting",
            "mass_or_product_gt_y": round(o2_gt, 3),
            "density_kg_m3": LIQUID_O2_DENSITY,
            "volume_km3_y": round(volume_km3(o2_gt, LIQUID_O2_DENSITY), 2),
            "additional_conversion_energy_gj_tco2": SPLITTING_ENERGY_GJ_T,
            "additional_conversion_energy_twh_y": round(energy_twh(SPLITTING_ENERGY_GJ_T), 0),
            "average_power_tw": round(energy_twh(SPLITTING_ENERGY_GJ_T) / 8760.0, 2),
            "interpretation": "Coproduct and safety burden, not a separate storage pathway.",
        },
        {
            "storage_state": "Magnesite-equivalent mineral carbonate",
            "mass_or_product_gt_y": round(magnesite_gt, 3),
            "density_kg_m3": MAGNESITE_DENSITY,
            "volume_km3_y": round(volume_km3(magnesite_gt, MAGNESITE_DENSITY), 2),
            "additional_conversion_energy_gj_tco2": "",
            "additional_conversion_energy_twh_y": "",
            "average_power_tw": "",
            "interpretation": "Durable and dense but material- and kinetics-constrained.",
        },
    ]
    write_csv(TABLE_DIR / "aether_conversion_state_ledger.csv", state_rows)

    split_rows = []
    for fraction in [0.0, 0.05, 0.10, 0.25, 0.50, 0.75, 1.0]:
        total_energy = CAPTURE_ENERGY_GJ_T + SPLITTING_ENERGY_GJ_T * fraction
        split_rows.append(
            {
                "split_fraction": fraction,
                "capture_energy_gj_tco2": CAPTURE_ENERGY_GJ_T,
                "splitting_energy_gj_tco2": round(SPLITTING_ENERGY_GJ_T * fraction, 3),
                "total_energy_gj_tco2": round(total_energy, 3),
                "annual_energy_twh_y": round(energy_twh(total_energy), 0),
                "average_power_tw": round(energy_twh(total_energy) / 8760.0, 2),
                "solid_carbon_gt_y": round(carbon_gt * fraction, 3),
                "solid_carbon_volume_km3_y": round(volume_km3(carbon_gt * fraction, GRAPHITE_DENSITY), 2),
                "liquid_o2_gt_y": round(o2_gt * fraction, 3),
                "liquid_o2_volume_km3_y": round(volume_km3(o2_gt * fraction, LIQUID_O2_DENSITY), 2),
            }
        )
    write_csv(TABLE_DIR / "aether_splitting_fraction_sensitivity.csv", split_rows)


if __name__ == "__main__":
    main()
